http {
    keepalive_timeout 5;
    
    server {
        listen 4244;
        listen 4245;
        server_name myWebserver someWebserver;
        root www;
        client_max_body_size 100000000;
        
        # Error pages
        error_page {
            400 www/error_pages/400.html
            403 www/error_pages/403.html
            404 www/error_pages/404.html
            405 www/error_pages/405.html
            418 www/error_pages/418.html
            500 www/error_pages/500.html
            502 www/error_pages/502.html
        }

        # Location blocks
        location /42 {
            return 301 http://42berlin.de/;
        }

        location /43 {
            autoindex on;
        }

        location /go {
            return 301 /here/index.html;
        }

        location /uploads {
            file_upload on;
        }

        # CGI Configuration
        cgi {
            cgi_path_alias /cgi-bin "/cgi-bin"
            upload_dir www/uploads
        }

        # Accepted Methods
        limit_except GET POST DELETE PUT {
            deny all;
        }
    }

    # Second server
    server {
        listen 4246;
        server_name myWebserver someWebserver;
        root ./www/html;
    }

    # Third server
    server {
        listen 4247;
        server_name myWebserver someWebserver;
		root ./www/html;
        # root www;
		# limit_except GET {
		# 	deny all;
		# }
		# index index.html;
		# location /go {
        #     return 301 /go/index.html;
        # }
    }

}