http {
	# Global settings
	maxBodySize 100000000; mandatory 
    maxConnections 100
    requestTimeout 60
    responseTimeout 60
    keepalive_timeout 60
    # Error pages - might be added by user or not - if not i have a default
    error_page {
        400 www/error_pages/400.html
        403 www/error_pages/403.html
        404 www/error_pages/404.html
        405 www/error_pages/405.html
        418 www/error_pages/418.html
        500 www/error_pages/500.html
        502 www/error_pages/502.html
    }
    
    server {
        listen 4244;
        listen 4245;
        server_name myWebserver someWebserver;
        root http/www1/;

        location /some/directory/ { 
            ... 
            index index.html  # List of files to try, in order
        }
        # TODO
        # Define a directory or a file from where the file should be searched (for example, if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet).

        # Directive/Location blocks
        # redirection
        location /42 {
            return 301 http://42berlin.de/;
        }

        location /43 {
            autoindex on;
            root /www2/;
        }

        # redirection
        location /go {
            return 301 /here/index.html;
        }

        location /here {
            limit_except GET POST DELETE PUT {
                deny all;
            }
        }
        # redirection /uploads/mydir -> www/http/mydir
        location /uploads {
            alias www/http
            file_upload on;
        }

        # CGI Configuration localhost:4244/cgi/test.cgi
        cgi {
            cgi_path_alias /cgi "/cgi-bin"
            upload_dir www/uploads
            file_extension .cgi .py
            limit_except GET POST DELETE PUT {
                deny all;
            }
        }


        location /mypictures {
            limit_except GET POST DELETE PUT {
                deny all;
            }
            file_upload on;
            file_upload_path /tmp/uploads;
        }


    }

    # Second server
    server2 {
        listen 4246;
        server_name myWebserver someWebserver;
        root ./www2;
    }

    # Third server
    server3 {
        listen 4247;
        server_name myWebserver someWebserver;
		root ./www/html;
    }

# ignored
    server4 {
        listen 4244;
        server_name myWebserver someWebserver;
        root ./www/html;
    }
}