# Basic configuration
ServerRoot "/usr/local/apache2"
Listen 4244
ServerAdmin webmaster@localhost
ServerName localhost:4244

# Set user and group for Apache processes
User www-data
Group www-data

# Load necessary modules
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule mime_module modules/mod_mime.so
LoadModule dir_module modules/mod_dir.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule alias_module modules/mod_alias.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so

# Main server configuration
DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

# Default directory index
DirectoryIndex index.html index.htm

# Redirect /go to /here
Redirect 301 /go /here

# Handle uploads directory
# The command that enables directory listing in Apache is Options Indexes.
<Directory "/usr/local/apache2/htdocs/uploads">
    Options Indexes FollowSymLinks
	# The AllowOverride None directive specifies that .htaccess files in this directory cannot override the configuration.
	AllowOverride None
	# The Require all granted directive specifies that all requests are allowed.
	Require all granted
# <FilesMatch "\.(jpg|jpeg|png|gif|pdf|txt)$">
#     Require all granted
# </FilesMatch>
# <FilesMatch "^(?!\.(jpg|jpeg|png|gif|pdf|txt)$)">
#     Require all denied
# </FilesMatch>
</Directory>

# CGI Configuration
ScriptAlias /cgi-bin/ "/usr/local/apache2/htdocs/cgi-bin/"
<Directory "/usr/local/apache2/htdocs/cgi-bin">
	AllowOverride None
	Options +ExecCGI
	AddHandler cgi-script .cgi .pl .py
	Require all granted    
</Directory>

# Error Pages
ErrorDocument 400 /error_pages/400.html
ErrorDocument 403 /error_pages/403.html
ErrorDocument 404 /error_pages/404.html
ErrorDocument 405 /error_pages/405.html
ErrorDocument 500 /error_pages/500.html
ErrorDocument 502 /error_pages/502.html
ErrorDocument 503 /error_pages/503.html
ErrorDocument 504 /error_pages/504.html

# File upload settings
LimitRequestBody 10485760 

# MIME Types
TypesConfig conf/mime.types
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz

# Logging
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /proc/self/fd/1 common
ErrorLog /proc/self/fd/2