events {
	worker_connections 1024; # max fd files open
}

http {

	keepalive_timeout 5;
	client_max_body_size 1000;

	# if I want to include these default headers in my responses
	add_header Content-Type "text/html";
    add_header Server "nginx/1.18.0";
    add_header Connection "keep-alive";

	server {
		# if ip addr not specified will listen to anyhost
		listen 4244; 
		listen 4245;  #second port
		# or listen 0:4244; # listen on all interfaces
		# or localhost:4244 # only localhost
		# or 0.0.0.0:4244 # all interfaces same as 0:4244
		# or *:4244 # all interfaces same as 0:4244
		# or listen 192.168.1.1:4244; # listen on a specific ip address
		# or listen 127.0.0.1:4244; # listen on a specific ip address

		server_name myWebserver someWebserver; # can have more than one server name
		client_max_body_size 1000;
		
		root /var/www/html;
		index index.html;

		# Custom error pages
		error_page 403 /custom403.html;
		error_page 404 /custom404.html;

		# Internal custom error pages - cannot be accessed directly - optional
		location /custom403.html {
			internal;
		}
		location /custom404.html {
			internal;
		}

		location /some/path {
			# location specific
			limit_except GET POST PUT DELETE {
				deny all;
			}
		}
		
		location / {
			# location specific
			client_max_body_size 1000;
			autoindex off;
		}

		location /42 {
			return 301 http://42berlin.de/;
		}

		location /43 {
			autoindex on;
		}
		

		# rerouting! the address in the bar remains the same - not a redirection
		location /here {
			alias /there/;
		}

		# redirection  -A 301 status code in HTTP is a "Moved Permanently" redirect
		location /go {
			return 301 here;
		}
		
		# Temporary redirect from /there to http:#42berlin.de/
		location /there {
			return 302 http://42berlin.de/;
		}

		location /special {
			# Custom error pages
			error_page 403 /super_custom403.html;
			error_page 404 /super_custom404.html;
		}
		
		#default for all server block if not other wise specified
		# limit_except GET {
		# 	deny all;
		# }
	}

	# each server block starts with server
	server {
		listen 4246;
		server_name myWebserver someWebserver;
		root /var/www/html;
	}

	server {
		listen 4247;
		server_name myWebserver someWebserver;
		root /var/www/html;
	}
}