events {
	worker_connections 1024; # max fd files open
}

http {

	keepalive_timeout 5;
	client_max_body_size 1000;

	# if I want to include these default headers in my responses
	add_header Content-Type "text/html";
    add_header Server "nginx/1.18.0";
    add_header Connection "keep-alive";

	
}