# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the appropriate Python version

    - name: Install venv module
      run: sudo apt-get install -y python3-venv

    - name: Build
      run: make

    - name: Build
      run: make test